de1:
  target: dev
  outputs:
    dev:
      type: clickhouse
      driver: http
      host: clickhouse
      port: 8123
      user: default
      password: ""
      schema: default
      secure: false
