FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip \
    && pip install dbt-core dbt-clickhouse

WORKDIR /usr/app

CMD ["sleep", "infinity"]